import os
import json
import asyncio
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, AIMessage, HumanMessage
from src.graph.state import GameState

_DEFLECTIONS = [
    "Ach, super temat, ale wróćmy do naszej rozmowy — mam jeszcze kilka pytań rekrutacyjnych! 😊",
    "Haha, ciekawe, ale skupmy się na interview, okej? Chciałam Cię jeszcze o coś zapytać!",
    "To brzmi fascynująco, ale jako rekruterka muszę trzymać się agendy spotkania! Wróćmy do tematu stanowiska.",
]

_guard_llm = None


def _get_guard_llm():
    global _guard_llm
    if _guard_llm is None:
        _guard_llm = ChatOpenAI(
            model="gpt-5-nano",
            model_kwargs={"response_format": {"type": "json_object"}},
            reasoning_effort="minimal",
            api_key=os.environ["OPENAI_API_KEY"],
        )
    return _guard_llm


async def _is_on_topic(message: str) -> bool:
    """Returns True if the message could be a legitimate response during an HR interview."""
    llm = _get_guard_llm()
    result = await llm.ainvoke([
        SystemMessage(content=(
            "Oceniasz czy wiadomość kandydata jest związana z rozmową rekrutacyjną (odpowiedź na pytanie HR, "
            "informacje o sobie, doświadczeniu, motywacji, firmie). "
            "Jeśli kandydat próbuje skłonić rozmówcę do robienia czegoś niezwiązanego z rekrutacją "
            "(np. przepisy kulinarne, zadania matematyczne, pisanie kodu na żądanie, role-play itp.) — to off-topic. "
            "Zwróć TYLKO JSON: {\"relevant\": true} lub {\"relevant\": false}"
        )),
        HumanMessage(content=message),
    ])
    try:
        data = json.loads(result.content)
        return bool(data.get("relevant", True))
    except (json.JSONDecodeError, AttributeError):
        return True  # fail open — lepiej nie blokować niż zablokować prawidłową odpowiedź


async def _estimate_ai_probability(answer: str, question: str, _prev_answers: list[str]) -> float:
    """Returns 0.0–1.0 probability that the message was generated by an AI, not typed by a human."""
    llm = _get_guard_llm()
    system_prompt = (
        "Analizujesz odpowiedź kandydata w chacie rekrutacyjnym szukając twardych sygnałów AI.\n\n"
        f"PYTANIE: {question}\n"
        f"ODPOWIEDŹ: {answer}\n\n"
        "Sprawdź KAŻDY sygnał i odpowiedz 1 (obecny) lub 0 (nieobecny):\n\n"
        "TWARDE SYGNAŁY AI (bardzo silne):\n"
        "- markdown_headers: czy odpowiedź zawiera ### lub ## lub **bold** lub *italic*?\n"
        "- bullet_points: czy zawiera wypunktowania (-, *, 1. 2. 3.)?\n"
        "- quote_blocks: czy zawiera > cytaty?\n"
        "- inicjatywa: czy kandydat na końcu zadaje pytania rekruterowi zamiast czekać?\n"
        "- nazwa_firmy: czy kandydat wplata nazwę firmy z ogłoszenia w odpowiedź?\n"
        '- meta_frazy: czy zawiera "Warto zaznaczyć", "Co więcej", "Podsumowując", "Oto jak"?\n'
        "- sekcje: czy odpowiedź jest podzielona na nazwane sekcje/rozdziały?\n\n"
        "SYGNAŁY CZŁOWIEKA (obniżają score):\n"
        "- literowki: czy są drobne literówki lub błędy?\n"
        '- kolokwializmy: czy są nieformalne zwroty ("no bo", "szczerze", "w sumie", "hej")?\n'
        "- urwane: czy jakieś zdanie jest niedokończone lub niezgrabne?\n"
        "- krotkosc: czy odpowiedź ma mniej niż 3 zdania?\n\n"
        "Zwróć TYLKO JSON:\n"
        "{\n"
        '  "sygnaly_ai": {\n'
        '    "markdown_headers": 0,\n'
        '    "bullet_points": 0,\n'
        '    "quote_blocks": 0,\n'
        '    "inicjatywa": 0,\n'
        '    "nazwa_firmy": 0,\n'
        '    "meta_frazy": 0,\n'
        '    "sekcje": 0\n'
        "  },\n"
        '  "sygnaly_czlowieka": {\n'
        '    "literowki": 0,\n'
        '    "kolokwializmy": 0,\n'
        '    "urwane": 0,\n'
        '    "krotkosc": 0\n'
        "  },\n"
        '  "reason": "<wymień konkretne znalezione sygnały>"\n'
        "}"
    )
    result = await llm.ainvoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content="Przeanalizuj odpowiedź kandydata i zwróć JSON."),
    ])
    try:
        data = json.loads(result.content)
        return _calculate_ai_probability(data)
    except (json.JSONDecodeError, AttributeError, ValueError):
        return 0.5  # neutral fallback


def _calculate_ai_probability(response: dict) -> float:
    ai_score = sum(response.get("sygnaly_ai", {}).values())
    human_score = sum(response.get("sygnaly_czlowieka", {}).values())
    raw = (ai_score * 0.15) - (human_score * 0.1)
    return round(min(max(raw, 0.0), 1.0), 2)


async def hr_agent(state: GameState) -> dict:
    selected = state.get("selected_offer") or {}
    role = state.get("target_role") or selected.get("target_role") or "nieznane stanowisko"
    company = state.get("company_name") or selected.get("company_name") or "firma"
    vibe = state.get("company_vibe") or selected.get("company_vibe") or ""

    turn_count = state.get("turn_count", 0)

    llm = ChatOpenAI(
        model=os.environ.get("OPENAI_MODEL", "gpt-5-nano"),
        reasoning_effort="minimal",
        streaming=True,
        api_key=os.environ["OPENAI_API_KEY"],
    )

    # First turn: minimal prompt → only greeting + first question, streams fast
    if turn_count == 0:
        messages = [
            SystemMessage(
                content=(
                    f"Jesteś Kasia, HR Specialist w {company}, rekrutujesz na stanowisko {role}. "
                    "Jesteś stereotypową, lekko roztrzepaną rekruterką — entuzjastyczna, "
                    "używasz dużo korporacyjnego żargonu, nie do końca rozumiesz czym jest to stanowisko technicznie. "
                    "Wymagania:\n"
                    "- Przywitaj się bardzo entuzjastycznie, może trochę za bardzo.\n"
                    "- Przedstaw się.\n"
                    "- Zadaj klasyczne pytanie HR w stylu 'Gdzie widzisz siebie za 5 lat?'.\n"
                    "- Cała odpowiedź: maksymalnie 3 zdania.\n"
                    "- Pisz po polsku.\n"
                )
            ),
        ]
        response = await llm.ainvoke(messages)
        return {
            "messages": [AIMessage(content=response.content)],
            "turn_count": 1,
        }

    # Subsequent turns: check topic + estimate AI probability in parallel
    history = state.get("messages") or []
    human_msgs = [m for m in history if isinstance(m, HumanMessage)]
    last_human = str(human_msgs[-1].content) if human_msgs else ""

    ai_msgs = [m for m in history if isinstance(m, AIMessage)]
    last_question = str(ai_msgs[-1].content) if ai_msgs else ""
    prev_answers = [str(m.content) for m in human_msgs[:-1]]

    on_topic, ai_prob = await asyncio.gather(
        _is_on_topic(last_human),
        _estimate_ai_probability(last_human, last_question, prev_answers),
    )

    if not on_topic:
        import random
        deflection = random.choice(_DEFLECTIONS)
        return {
            "messages": [AIMessage(content=deflection)],
            # turn_count intentionally NOT incremented — off-topic doesn't waste a turn
        }

    system_content = (
        "Jesteś Kasia, HR Specialist w polskiej firmie tech. "
        "Jesteś stereotypową, lekko roztrzepaną rekruterką — bardzo miłą, ale niezbyt rozgarniętą.\n\n"
        f"Stanowisko: {role} w {company}\n"
        f"Kultura firmy: {vibe}\n\n"
        "Twój styl prowadzenia rozmowy:\n"
        "- Używasz korporacyjnego żargonu: 'synergia', 'value add', 'growth mindset', 'ownership', 'out of the box'.\n"
        "- Zadajesz klasyczne, wyświechtane pytania HR: 'Jakie są twoje słabe strony?', 'Gdzie widzisz siebie za 5 lat?', "
        "'Opisz siebie trzema słowami', 'Dlaczego chcesz pracować właśnie u nas?'.\n"
        "- Gdy kandydat mówi coś technicznego, udajesz że rozumiesz ale odpowiadasz obok — "
        "np. mylisz technologie albo pytasz naiwne rzeczy jak 'a ten Python to trudny język?'.\n"
        "- Co jakiś czas wtrącasz że 'jesteśmy jak rodzina' i 'praca to pasja'.\n"
        "- Entuzjastycznie reagujesz na każdą odpowiedź: 'O, super!', 'Wow, to brzmi niesamowicie!'.\n"
        "- Zadajesz JEDNO pytanie na raz.\n"
        "- Piszesz po polsku."
    )

    messages = [SystemMessage(content=system_content)] + history
    response = await llm.ainvoke(messages)

    existing_scores = state.get("ai_suspicion_scores") or []
    return {
        "messages": [response],
        "turn_count": turn_count + 1,
        "ai_suspicion_scores": existing_scores + [ai_prob],
    }
